import test from 'node:test';import assert from 'node:assert/strict';
import worker from '../src/worker.js';import {encrypt,decrypt,safeUrl,validScreenshot} from '../src/security.js';
const key=btoa('x'.repeat(32));const env={SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public',CONTENT_KEY:key,AI_ENABLED:'true',AI_MODEL:'model'};
const req=(path,body,options={})=>new Request('https://app.test/api/'+path,{method:'POST',headers:{Origin:'https://app.test',Authorization:'Bearer token',...options.headers},body:typeof body==='string'?body:JSON.stringify(body)});
async function mocked(fn,{authOK=true,items=[],history=[],budget={reason:null},budgetOK=true,aiError=false,articleBlocked=false,response='Saved evidence [1]'}={}){
 const original=globalThis.fetch;let aiCalls=0,reservations=0,lastAiInput;const calls=[];
 globalThis.fetch=async(url,opts)=>{calls.push({url,opts});if(articleBlocked&&url.includes('dns-query'))return Response.json({Status:0,Answer:[{type:1,data:'8.8.8.8'}]});if(articleBlocked&&url.startsWith('https://news.com/'))return new Response(null,{status:403});if(url.endsWith('/auth/v1/user'))return authOK?Response.json({id:'alice'}):Response.json({}, {status:401});if(url.includes('memories?'))return Response.json(items);if(url.includes('chat_messages?'))return Response.json(history);return Response.json([{id:'new',created_at:'2026-10-03'}]);};
 const configured={...env,AI:{run:async(model,input)=>{lastAiInput=input;aiCalls++;if(aiError)throw Error('private provider detail');return {response};}},AI_BUDGET:{idFromName:()=>1,get:()=>({fetch:async()=>{reservations++;return Response.json(budget,{status:budgetOK?200:500});}})}};
 try{await fn(configured,()=>({aiCalls,reservations,calls,lastAiInput}));}finally{globalThis.fetch=original;}
}
const source=async()=>[{id:'gpu',created_at:'2026-10-03',payload:await encrypt({title:'GPU',content:'16 GB VRAM',tags:[]},key,'alice')}];
test('bulk deletion is one owner-scoped hard delete and leaves chat untouched',async()=>{await mocked(async(e,stats)=>{
 const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222'];
 const request=new Request('https://app.test/api/memories',{method:'DELETE',headers:{Origin:'https://app.test',Authorization:'Bearer token'},body:JSON.stringify({ids,user_id:'bob'})});
 assert.equal((await worker.fetch(request,e)).status,200);const writes=stats().calls.filter(c=>c.opts?.method==='DELETE');assert.equal(writes.length,1);assert(writes[0].url.includes('user_id=eq.alice&id=in.('+ids.join(',')+')'));assert(!writes[0].url.includes('chat_messages'));
 });});
test('invalid bulk selections cannot reach a storage deletion',async()=>{await mocked(async(e,stats)=>{
 for(const ids of [[],['bad),user_id=eq.bob'],Array(201).fill('11111111-1111-4111-8111-111111111111'),[null]])assert.equal((await worker.fetch(new Request('https://app.test/api/memories',{method:'DELETE',headers:{Origin:'https://app.test',Authorization:'Bearer token'},body:JSON.stringify({ids})}),e)).status,400);
 assert.equal(stats().calls.filter(c=>c.opts?.method==='DELETE').length,0);
 });});
test('expired tokens reject every private endpoint before storage',async()=>{await mocked(async(e,stats)=>{for(const path of ['chat','memories','account','data']){const r=await worker.fetch(req(path,{}),e);assert.equal(r.status,401);}assert.equal(stats().calls.length,4);assert.equal(stats().aiCalls,0);},{authOK:false});});
test('malformed and non-object JSON fail cleanly without writes',async()=>{await mocked(async e=>{for(const body of ['{','null','[]','true','42','"hello"'])assert.equal((await worker.fetch(req('memories',body),e)).status,400);});});
test('blank, oversized and non-string chat questions use no AI',async()=>{await mocked(async(e,stats)=>{for(const message of [' ',{},'What '+ 'x'.repeat(1001)])assert.equal((await worker.fetch(req('chat',{message}),e)).status,400);assert.equal(stats().aiCalls,0);});});
test('untrusted image formats and empty notes are rejected',async()=>{await mocked(async e=>{for(const body of [{type:'video'},{type:'note',content:'   '},{type:'screenshot',image:'data:image/svg+xml;base64,AAAA'},{type:'screenshot',image:'https://evil.test/image.png'},{type:'article',url:'javascript:alert(1)'}])assert.equal((await worker.fetch(req('memories',body),e)).status,400);});});
test('memory cap blocks another insert',async()=>{const rows=await source();await mocked(async e=>{assert.equal((await worker.fetch(req('memories',{type:'note',content:'test'}),e)).status,429);},{items:Array.from({length:200},()=>rows[0])});});
test('quota refusal and broken budget never invoke AI',async()=>{for(const reason of ['global','daily','burst'])await mocked(async(e,stats)=>{assert.equal((await worker.fetch(req('chat',{message:'Summarize saved GPU'}),e)).status,429);assert.equal(stats().aiCalls,0);},{items:await source(),budget:{reason}});await mocked(async(e,stats)=>{assert.equal((await worker.fetch(req('chat',{message:'Summarize saved GPU'}),e)).status,503);assert.equal(stats().aiCalls,0);},{items:await source(),budgetOK:false});});
test('provider errors are sanitized, have no retries, and reserve only once',async()=>{await mocked(async(e,stats)=>{const r=await worker.fetch(req('chat',{message:'Summarize saved GPU'}),e);assert.equal(r.status,503);assert(!JSON.stringify(await r.json()).includes('private provider detail'));assert.equal(stats().aiCalls,1);assert.equal(stats().reservations,1);},{items:await source(),aiError:true});});
test('unfinished model reasoning is not shown to the user',async()=>{await mocked(async e=>{assert.equal((await worker.fetch(req('chat',{message:'Summarize saved GPU'}),e)).status,503);},{items:await source(),response:'<think>private reasoning without closing tag'});});
test('successful chat stores encrypted owner-bound content',async()=>{await mocked(async(e,stats)=>{const r=await worker.fetch(req('chat',{message:'Summarize saved GPU'}),e);assert.equal(r.status,200);const writes=stats().calls.filter(c=>c.url.endsWith('/chat_messages'));assert.equal(writes.length,2);for(const {opts}of writes){const row=JSON.parse(opts.body);assert.equal(row.user_id,'alice');assert(!opts.body.includes('Saved evidence'));await assert.rejects(decrypt(row.payload,key,'bob'));}},{items:await source()});});
test('chat history retrieves recent messages in chronological display order',async()=>{const history=await Promise.all(['new','old'].map(async text=>({payload:await encrypt({role:'user',content:text},key,'alice')})));await mocked(async(e,stats)=>{const r=await worker.fetch(new Request('https://app.test/api/chat',{headers:{Authorization:'Bearer token'}}),e);assert.deepEqual((await r.json()).messages.map(m=>m.content),['old','new']);assert(stats().calls[1].url.includes('order=created_at.desc'));},{history});});
test('tampered ciphertext cannot be decrypted',async()=>{const cipher=await encrypt({content:'secret'},key,'alice');cipher.data='AAAA'+cipher.data.slice(4);await assert.rejects(decrypt(cipher,key,'alice'));});
test('encoded IPs and credential tricks are rejected',()=>{for(const url of ['https://2130706433','https://0x7f000001','https://0177.0.0.1','https://user@news.com','https://news.com@127.0.0.1'])assert.throws(()=>safeUrl(url));});

test('image validation checks byte signatures and base64 integrity',()=>{
 assert.equal(validScreenshot('data:image/png;base64,'+btoa('not a PNG')),false);
 assert.equal(validScreenshot('data:image/png;base64,AAAA==='),false);
 assert.equal(validScreenshot('data:image/png;base64,'+btoa('\x89PNG\r\n\x1a\n'+'bytes')),true);
 assert.equal(validScreenshot('data:image/jpeg;base64,'+btoa('\xff\xd8\xff'+'bytes')),true);
 assert.equal(validScreenshot('data:image/webp;base64,'+btoa('RIFF0000WEBPbytes')),true);
});
test('greetings use the AI budget and model even without saved sources',async()=>{await mocked(async(e,stats)=>{const r=await worker.fetch(req('chat',{message:'hi'}),e);assert.equal(r.status,200);assert.equal(stats().aiCalls,1);assert.equal(stats().reservations,1);});});

test('blocked publishers save an unread link without inventing article content',async()=>{await mocked(async(e,stats)=>{const r=await worker.fetch(req('memories',{type:'article',url:'https://news.com/article',dump:true}),e);assert.equal(r.status,201);const data=await r.json();assert.equal(data.item.status,'needs-content');assert.equal(data.item.content,'');assert.equal(data.acknowledgment,'Saved.');const write=stats().calls.find(c=>c.url.endsWith('/memories')&&c.opts.method==='POST');const stored=await decrypt(JSON.parse(write.opts.body).payload,key,'alice');assert.equal(stored.captureIssue,'blocked');},{articleBlocked:true,response:'Link saved, but the publisher blocked access. Add article text to summarize it.'});});
test('pasted article text updates the same owner-bound record without a duplicate',async()=>{const id='11111111-1111-4111-8111-111111111111';const item={type:'article',title:'news.com',url:'https://news.com/article',content:'',tags:[],status:'needs-content',captureIssue:'blocked'};await mocked(async(e,stats)=>{const r=await worker.fetch(new Request('https://app.test/api/memories/'+id,{method:'PATCH',headers:{Origin:'https://app.test',Authorization:'Bearer token'},body:JSON.stringify({content:'User supplied article text',user_id:'bob'})}),e);assert.equal(r.status,200);assert.equal((await r.json()).item.id,id);const writes=stats().calls.filter(c=>c.opts?.method==='PATCH');assert.equal(writes.length,1);assert(writes[0].url.includes('user_id=eq.alice&id=eq.'+id));const saved=await decrypt(JSON.parse(writes[0].opts.body).payload,key,'alice');assert.equal(saved.status,'saved');assert.equal(saved.captureIssue,undefined);assert.equal(saved.content,'User supplied article text');},{items:[{id,created_at:'2026-10-03',payload:await encrypt(item,key,'alice')}]});});

test('Chat never turns supplied links or text into saved dumps',async()=>{await mocked(async(e,stats)=>{assert.equal((await worker.fetch(req('chat',{message:'https://news.com/article'}),e)).status,200);assert.equal(stats().calls.filter(c=>c.url.endsWith('/memories')&&c.opts?.method==='POST').length,0);});});
test('dump acknowledgments are brief and never create a chat turn',async()=>{await mocked(async(e,stats)=>{const r=await worker.fetch(req('memories',{type:'note',content:'My real-world note',dump:true}),e);assert.equal(r.status,201);assert.equal((await r.json()).acknowledgment,'Noted and saved.');assert.equal(stats().calls.filter(c=>c.url.endsWith('/chat_messages')).length,0);assert.equal(stats().aiCalls,1);},{response:'Noted and saved.'});});

test('AI acknowledgment quota exhaustion does not prevent saving a dump',async()=>{await mocked(async(e,stats)=>{const r=await worker.fetch(req('memories',{type:'note',content:'Save this even without AI allowance',dump:true}),e);assert.equal(r.status,201);assert.equal((await r.json()).acknowledgment,'Saved.');assert.equal(stats().aiCalls,0);},{budget:{reason:'daily'}});});

test('inventory follow-up supplies every saved title and exact count instead of prior wrong answers',async()=>{const titles=['Washington Post link','Druski story','Weight-loss drugs','G7 fuel reserves'];const rows=await Promise.all(titles.map(async(title,index)=>({id:String(index),created_at:new Date().toISOString(),payload:await encrypt({type:'article',title,content:index?'Article text':'',status:index?'saved':'needs-content',tags:[]},key,'alice')})));const history=await Promise.all([{role:'assistant',content:'You saved one item today.'},{role:'user',content:'what did i save today?'}].map(async msg=>({payload:await encrypt(msg,key,'alice')})));await mocked(async(e,stats)=>{const r=await worker.fetch(req('chat',{message:'is that all i saved?',timeZone:'America/Chicago'}),e);assert.equal(r.status,200);const input=stats().lastAiInput,data=JSON.parse(input.messages.at(-1).content);assert.equal(data.inventory.count,4);assert.equal(data.sources.length,4);assert.equal(input.messages.length,2);assert(data.sources.some(source=>source.status==='needs-content'));},{items:rows,history});});
