import test from 'node:test';import assert from 'node:assert/strict';import {sessionEndpoint} from '../src/session.js';
const env={SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public'};
async function mock(fn,fetcher){const old=globalThis.fetch;globalThis.fetch=fetcher;try{await fn()}finally{globalThis.fetch=old}}
test('code exchange puts tokens in secure HttpOnly cookies, never response JSON',async()=>{await mock(async()=>{const res=await sessionEndpoint(new Request('https://app.test/api/session',{method:'POST',headers:{Origin:'https://app.test'},body:JSON.stringify({auth_code:'code',code_verifier:'verifier'})}),env);const body=await res.json();assert.equal(body.session.user.id,'alice');assert(!JSON.stringify(body).includes('private'));const cookies=res.headers.get('Set-Cookie');assert(cookies.includes('HttpOnly'));assert(cookies.includes('Secure'));assert(cookies.includes('SameSite=Lax'));assert(cookies.includes('__Host_bd_access'));},async()=>Response.json({access_token:'private-access',refresh_token:'private-refresh',expires_in:3600,user:{id:'alice'}}));});
test('reload recovers user from existing session cookie',async()=>{await mock(async()=>{const res=await sessionEndpoint(new Request('https://app.test/api/session',{headers:{Cookie:'__Host_bd_access=access'}}),env);assert.equal((await res.json()).session.user.id,'alice');},async()=>Response.json({id:'alice'}));});
test('expired access refreshes and rotates both cookies',async()=>{let calls=0;await mock(async()=>{const res=await sessionEndpoint(new Request('https://app.test/api/session',{headers:{Cookie:'__Host_bd_access=old; __Host_bd_refresh=refresh'}}),env);assert.equal((await res.json()).session.user.id,'alice');assert(res.headers.get('Set-Cookie').includes('new-access'));assert.equal(calls,2);},async url=>{calls++;return url.endsWith('/user')?Response.json({}, {status:401}):Response.json({access_token:'new-access',refresh_token:'new-refresh',user:{id:'alice'}})});});
test('cross-origin session mutations are rejected',async()=>{for(const method of ['POST','DELETE'])assert.equal((await sessionEndpoint(new Request('https://app.test/api/session',{method,headers:{Origin:'https://evil.test'}}),env)).status,403);});
test('logout clears cookies and revokes access',async()=>{let revoked=false;await mock(async()=>{const res=await sessionEndpoint(new Request('https://app.test/api/session',{method:'DELETE',headers:{Origin:'https://app.test',Cookie:'__Host_bd_access=access'}}),env);assert.equal((await res.json()).session,null);assert(res.headers.get('Set-Cookie').includes('Max-Age=0'));assert(revoked);},async()=>{revoked=true;return new Response(null,{status:204})});});
test('temporary auth outages do not clear cookies',async()=>{await mock(async()=>{const res=await sessionEndpoint(new Request('https://app.test/api/session',{headers:{Cookie:'__Host_bd_access=access'}}),env);assert.equal(res.status,503);assert.equal(res.headers.get('Set-Cookie'),null);},async()=>Response.json({}, {status:503}));});
