import test from 'node:test';import assert from 'node:assert/strict';import worker from '../src/worker.js';
const env={SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public',CONTENT_KEY:'configured'};
test('configuration exposes only public settings',async()=>{const res=await worker.fetch(new Request('https://app.test/api/config'),env);const body=await res.json();assert.equal(body.ready,true);assert.equal(body.CONTENT_KEY,undefined);assert.equal(res.headers.get('Cache-Control'),'no-store');assert.equal(res.headers.get('X-Frame-Options'),'DENY')});
test('API rejects unauthenticated access before touching storage',async()=>{const res=await worker.fetch(new Request('https://app.test/api/memories'),env);assert.equal(res.status,401)});
test('cross-origin mutations are rejected',async()=>{const res=await worker.fetch(new Request('https://app.test/api/memories',{method:'POST',headers:{Origin:'https://attacker.test'},body:'{}'}),env);assert.equal(res.status,403)});
test('unconfigured cloud cannot accept private data',async()=>{const res=await worker.fetch(new Request('https://app.test/api/memories',{method:'POST',body:'{}'}),{});assert.equal(res.status,503)});
test('account deletion requires authentication and a same-origin request',async()=>{const res=await worker.fetch(new Request('https://app.test/api/account',{method:'DELETE',headers:{Origin:'https://app.test'}}),env);assert.equal(res.status,401);const cross=await worker.fetch(new Request('https://app.test/api/account',{method:'DELETE',headers:{Origin:'https://attacker.test',Authorization:'Bearer token'}}),env);assert.equal(cross.status,403)});
test('account deletion calls only the caller-bound RPC and ignores a supplied target ID',async()=>{const original=globalThis.fetch;const calls=[];globalThis.fetch=async(url,options)=>{calls.push({url,options});return url.endsWith('/auth/v1/user')?Response.json({id:'caller'}):new Response(null,{status:204})};try{const res=await worker.fetch(new Request('https://app.test/api/account',{method:'DELETE',headers:{Origin:'https://app.test',Authorization:'Bearer user-token'},body:JSON.stringify({user_id:'someone-else'})}),env);assert.equal(res.status,200);assert.equal(calls[1].url,'https://project.supabase.co/rest/v1/rpc/delete_my_account');assert.equal(calls[1].options.body,'{}');assert.equal(calls[1].options.headers.Authorization,'Bearer user-token')}finally{globalThis.fetch=original}});
test('disabled AI fallback avoids inference and budget reservations',async()=>{
 const original=globalThis.fetch;let aiCalls=0,budgetCalls=0;
 const configured={...env,CONTENT_KEY:btoa('x'.repeat(32)),AI_ENABLED:'false',AI:{run:async()=>{aiCalls++;}},AI_BUDGET:{idFromName:()=>1,get:()=>({fetch:async()=>{budgetCalls++;}})}};
 globalThis.fetch=async url=>url.endsWith('/auth/v1/user')?Response.json({id:'caller'}):Response.json([]);
 try{for(const message of ['Write me a poem','What did I save about gardening?']){
 const res=await worker.fetch(new Request('https://app.test/api/chat',{method:'POST',headers:{Origin:'https://app.test',Authorization:'Bearer token'},body:JSON.stringify({message})}),configured);assert.equal(res.status,200);
 }assert.equal(aiCalls,0);assert.equal(budgetCalls,0);}finally{globalThis.fetch=original}
});
